name = "Polynomials"
uuid = "40aba029-825d-41bd-a97e-db86442ba04f"
authors = ["Alcyon Lab"]
version = "1.0.1-DEV"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"

[compat]
julia = "1.2"
